website/models.py
from . import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True, nullable="False")
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    games = db.relationship('Game', backref='user') 
    #user.games[0] -> lista gier
    

class Game(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    winner = db.Column(db.String(150))
    time = db.Column(db.String(150))
    score = db.Column(db.String(20))
    #plansza = db.Column(db.String())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    #players = db.Column(db.) //todo
    #game.user.first_name-nazwa

website/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'According to all known laws of aviation'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth
    from .game import game


    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(game)

    from .models import User

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    #obsługa błędu 404
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('404.html'), 404

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from .models import User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
auth = Blueprint('auth', __name__)

@auth.route('/', methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        email = request.form.get('userName')
        password = request.form.get('userPassword')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect(url_for("views.main", user=current_user ))
            else:
                #niepoprawne haslo
                return render_template("login.html", message="Niepoprawne hasło")
        else:
            #nie ma takiego maila
            return render_template("login.html", message="Niepoprawny adres email")


    return render_template("login.html", user=current_user)


@auth.route('/new_account', methods = ['GET', 'POST'])
def new_account():
    if request.method == 'POST':
        email = request.form.get('userEmail')
        first_name = request.form.get('userName')
        password = request.form.get('userPassword')

        user = User.query.filter_by(email=email).first()
        if user:
            # email zajety
            return render_template("new_account.html", message="Email zajety")
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            return redirect('/main')

    return render_template("new_account.html")

@auth.route('/logout',  methods = ['POST', 'GET'])
@login_required
def logout():
    logout_user()
    return redirect('/')

website/views.py
from flask import Blueprint, render_template
from flask_login import login_required

views = Blueprint('views', __name__)

@views.route('/main', methods=['POST', 'GET'])
@login_required
def main():
    return render_template("main.html")

website/templates/game.html
<!DOCTYPE html>
<html lang="pl">

<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="utf-8">
    <link rel="stylesheet" href="../static/styles.css">
    <link rel="icon" type="image/x-icon" href="../static/img/favicon.png">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
        integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <title>Skrabble- rozgrywka</title>

</head>

<body>

    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Koniec Gry</h5>
                </div>
                <div class="modal-body">
                    <P id="infoWygrana"></P>
                </div>
                <div class="modal-footer">
                    <button type="button" id ="koniecGryBtn" class="btn btn-danger" data-bs-dismiss="modal">Zakończ rozgrywkę</button>
                </div>
            </div>
        </div>
    </div>

    <!--tło-->
    <div class='box'>
        <div class='wave -one'></div>
        <div class='wave -two'></div>
        <div class='wave -three'></div>
    </div>

    <!--nagłówek-->
    <div class="container-fluid text-center">
        <img src="../static/img/logo.png">
    </div>

    <div style="position: absolute; width:100%; height: 100%; margin: 0%;">

        <!--Tabela z wynikami-->
        <div style="position: absolute; width: 40%; left: 1%; top: 4%; " id="divTabela">
            <div class="card" style="position: absolute;
            top: 50%;
            width: 100%;
            text-align: center;
            font-size: 18px;
            background-color: dodgerblue;
            border-radius: 25px;">
                <div class="card-body">
                    <h4 class="card-title">Nazwa pokoju: <b id="numerInfo"></b>. Witaj <b
                            id="userNameinfo">{{current_user.first_name}}!</b></h4>
                    <p id="czyjaTuraInfo"></p>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col-sm">Nazwa gracza</th>
                                <th scope="col-sm">Wynik</th>
                                <th scope="col-sm">Punkty do zwyciestwa</th>
                            </tr>
                        </thead>
                        <tbody id="listaUzytkownikow">
                        </tbody>
                    </table>

                </div>
                <div class="card-footer"></div>
            </div>
        </div>

        <!--div z reka-->
        <div style="position: absolute; width: 40%; left: 1%; top:56%" id="divLitery">
            <div class="card" style="position: absolute;
            top: 50%;
            width: 100%;
            text-align: center;
            font-size: 18px;
            background-color: dodgerblue;
            border-radius: 25px;">
                <div class="card-header">
                    <div class=" ms-3 btn btn-dark" style="display: inline-block;" id="cofnijRuchBtn"
                        onclick="return cofnijRuch();">Cofnij ruch
                    </div>
                    <div class=" ms-3 btn btn-info" style="display: inline-block;" id="wymienLitereBtn"
                        onclick="return wymienLitere();">Wymień literę
                    </div>
                    <div class=" ms-3 btn btn-success" style="display: inline-block;" id="potwierdzRuchBtn"
                        onclick="return potwierdzRuch();">Potwierdź
                        ruch</div>
                    <div class=" ms-3 btn btn-danger" style="display: inline-block;" id="pominTureBtn">Pomiń turę</div>
                </div>
                <div class="card-body">
                    <div class="container" id="rekaDiv">
                    </div>
                </div>
                <div class="card-footer"></div>

            </div>
        </div>

        <!--plansza-->
        <div class="card text-center"
            style="position: absolute; width: 54%; left: 45%; top: 4%; height: 82%; background-color: dodgerblue; border-radius: 25px;"
            id="plansza">
            <div class="card-body">
                <div class="container" id="planszaDiv">
                </div>
            </div>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="../static/scripts/game.js"></script>
</body>


</html>

website/templates/login.html
<!DOCTYPE html>
<html lang="pl">

<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="utf-8">
    <link rel="stylesheet" href="../static/styles.css">
    <link rel="icon" type="image/x-icon" href="../static/img/favicon.png">
    <title>Skrabble- logowanie</title>

</head>

<body>

    <!--tło-->
    <div class='box'>
        <div class='wave -one'></div>
        <div class='wave -two'></div>
        <div class='wave -three'></div>
    </div>

    <!--nagłówek-->
    <div class="container-fluid text-center">
        <img src="../static/img/logo.png">
    </div>

    <!--karta do logowania-->
    <div class="container" style="position: relative; width: 30%; margin-top: 10%;">
        <div class="card" style="position: absolute;
        top: 50%;
        width: 100%;
        text-align: center;
        font-size: 18px;
        background-color: dodgerblue;
        border-radius: 25px;">
            <div class="card-body">
                <h4 class="card-title">Zaloguj sie</h4>
            </div>
            <div class="card-body">
                <form name="frm" action="{{ url_for('auth.login') }}" method="post">
                    <!--TODO do czego wysyłam formularz-->
                    <div class="form-group my-2">
                        <label for="userName">Email użytkownika</label>
                        <input name="userName" type="text" class="form-control my-2" id="userName"
                            placeholder="Podaj email użytkownika">
                    </div>
                    <div class="form-group mt-2 mb-0">
                        <label for="userPassword">Hasło</label>
                        <input name="userPassword" type="password" class="form-control my-2" id="userPassword"
                            placeholder="Podaj hasło">
                        {% if message == "Niepoprawny adres email" %}
                        <small name="warrning" id="passSame" class="form-text text-danger"
                            style="visibility: visable; position: absolute; bottom: 28%; left: 3%;text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue">
                            Niepoprawny adres email!
                        </small>
                        {% elif message == "Niepoprawne hasło" %}
                        <small name="warrning" id="passSame" class="form-text text-danger"
                            style="visibility: visable; position: absolute; bottom: 28%; left: 3%;text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue">
                            Niepoprawne hasło!
                        </small>
                        {% else %}
                        <small name="warrning" id="passSame" class="form-text text-danger"
                            style="visibility: hidden; position: absolute; bottom: 28%; left: 3%;text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue">
                        </small>
                        {% endif %}
                    </div>
                    <input class="btn btn-primary mt-4" type="submit" id="submitButton" value="Zaloguj"
                        onclick="return isValid();">
                </form>
            </div>
            <div class="card-footer">Nie masz konta? <a class="text-dark fw-bold" href="/new_account">Zarejestruj
                    sie!</a></div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="../static/scripts/login.js"></script>
</body>


</html>

website/templates/main.html
<!DOCTYPE html>
<html lang="pl">

<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
        integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../static/styles.css">
    <link rel="icon" type="image/x-icon" href="../static/img/favicon.png">
    <title>Skrabble- strona główna</title>

</head>

<body>

    <!-- Modal 0 stworz gre -->
    <div class="modal fade" id="staticBackdrop0" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel0" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel0">Stwórz nową sesje i zaproś znajomych</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form name="frm" action="#" method="post">
                        <!--TODO do czego wysyłam formularz-->
                        <div class="form-group my-2">
                            <label for="roomName">Numer pokoju</label>
                            <input name="roomName" type="text" class="form-control my-2" id="roomName"
                                placeholder="Podaj numer pokoju">
                        </div>
                        <div class="form-group mt-2 mb-0">
                            <label for="roomPassword">Hasło pokoju</label>
                            <input name="roomPassword" type="text" class="form-control my-2" id="roomPassword"
                                placeholder="Podaj hasło">
                            <small name="warrning" id="wrongPass" class="form-text text-danger"
                                style="visibility:hidden; position: absolute; bottom: 3%; left: 3.5%;text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue"></small>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <label for="submitButton" tabindex="0" class="btn btn-success" type="button" id="joinGameModal"
                        onclick="return isValid(0);">Zacznij gre!</label>
                    <!--TODO może nie działać bo submit poza formem, naprawa to z powrotem dać to do wnetrza forma  -->
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal"
                        onclick="return resetForm(0);">Zamknij</button>
                </div>
            </div>
        </div>
    </div>
    </div>

    <!-- Modal 1 dolacz do gry-->
    <div class="modal fade" id="staticBackdrop1" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel1">Dołącz do istniejącej gry</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form name="frm" action="#" method="post">
                        <!--TODO do czego wysyłam formularz-->
                        <div class="form-group my-2">
                            <label for="roomName1">Numer pokoju</label>
                            <input name="roomName1" type="text" class="form-control my-2" id="roomName1"
                                placeholder="Podaj numer pokoju">
                        </div>
                        <div class="form-group mt-2 mb-0">
                            <label for="roomPassword1">Hasło pokoju</label>
                            <input name="roomPassword1" type="text" class="form-control my-2" id="roomPassword1"
                                placeholder="Podaj hasło">
                            <small name="warrning1" id="wrongPass1" class="form-text text-danger"
                                style="visibility:hidden; position: absolute; bottom: 3%; left: 3.5%;text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue"></small>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <label for="submitButton1" tabindex="0" class="btn btn-success" type="button" id="joinGameModal1"
                        onclick="return isValid(1);">Dołącz</label>
                    <!--TODO może nie działać bo submit poza formem, naprawa to z powrotem dać to do wnetrza forma  -->
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal"
                        onclick="return resetForm(1);">Zamknij</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal 2 historia gier -->
    <div class="modal fade" id="staticBackdrop2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel2" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel2">Historia twoich rozgrywek</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% if current_user.games == null %}
                    Ups... Wygląda na to że nie rozegrałeś jeszcze żadnej gry. Nic straconego! Kliknij w Stwórz nową grę
                    lub dołącz do już trwającej rozgrywki ze znajomym!

                    {% else %}
                    <table class="table">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col-sm">Wygrany</th>
                                <th scope="col-sm">Data</th>
                                <th scope="col-sm">Wynik</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in current_user.games %}
                            {% if item.winner == current_user.first_name %}
                            <tr class="table-success">
                                {% else %}
                            <tr class="table-danger">
                                {% endif %}
                                <td>{{item.winner}}</td>
                                <td>{{item.time}}</td>
                                <td>{{item.score}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    {% endif %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Zamknij</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal 3 jak grac -->
    <div class="modal fade" id="staticBackdrop3" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel3" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel3">Zasady gry</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!--TODO tu będzie jinja generować to co chcemy -->
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget dolor in justo aliquet egestas sed
                    quis dolor. Praesent congue mi vitae tempus tincidunt. Suspendisse potenti. Quisque at ex viverra
                    nisi consectetur iaculis vel vel est. Phasellus vestibulum at turpis at efficitur. Vivamus sem enim,
                    dictum vel massa nec, pretium tincidunt urna. Aliquam nibh lorem, venenatis non consectetur sit
                    amet, iaculis quis massa.

                    Mauris ac luctus odio, vel tempus justo. Cras lorem ex, imperdiet ut mi eu, aliquam ullamcorper
                    turpis. Aliquam pharetra eleifend turpis ac feugiat. Suspendisse ligula diam, bibendum vel
                    pellentesque non, suscipit a sapien. Quisque et magna tellus. Aliquam non tellus ex. Proin maximus a
                    ante sed ornare. Nunc non ultricies tellus. Mauris eu augue venenatis, mollis quam a, tristique
                    sapien. Sed molestie urna in ex elementum facilisis. Fusce turpis lectus, molestie eget faucibus eu,
                    tristique gravida magna.

                    Pellentesque sed nunc a mauris blandit varius. Nunc porttitor, lacus eget semper viverra, nisi felis
                    dictum dui, ac maximus magna ligula a ipsum. Curabitur ut viverra felis. Quisque varius commodo
                    nunc. Aliquam vehicula quis eros dapibus auctor. Suspendisse venenatis tellus vel lectus volutpat,
                    non condimentum lorem rutrum. Duis gravida sodales diam eget commodo. Maecenas porta maximus risus,
                    et faucibus lectus fermentum a. Donec eros sem, suscipit ut condimentum in, consectetur vitae sem.
                    Mauris purus ante, malesuada quis porta sit amet, mollis a erat. Interdum et malesuada fames ac ante
                    ipsum primis in faucibus.

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Zamknij</button>
                </div>
            </div>
        </div>
    </div>

    <!--tło-->
    <div class='box'>
        <div class='wave -one'></div>
        <div class='wave -two'></div>
        <div class='wave -three'></div>
    </div>

    <!--nagłówek-->
    <div class="container-fluid text-center">
        <img src="../static/img/logo.png">
    </div>

    <!--karta do logowania-->
    <div class="container" style="position: relative; width: 30%; margin-top: 6%;">
        <div class="card" style="position: absolute;
        top: 50%;
        width: 100%;
        text-align: center;
        font-size: 18px;
        background-color: dodgerblue;
        border-radius: 25px;">
            <div class="card-header">
                <h4 class="card-title mt-2">Witaj {{current_user.first_name}}!</h4>
            </div>
            <div class="card-body">
            </div>
            <div class="card-body">
                <div class="menuBtn">
                    <button id="createGame" class="btn btn-primary" style="width: 70%;" data-bs-toggle="modal"
                        data-bs-target="#staticBackdrop0">Stwórz nową grę</button>
                </div>
                <div class="menuBtn">
                    <button id="joinGame" class="btn btn-primary" style="width: 70%;" data-bs-toggle="modal"
                        data-bs-target="#staticBackdrop1">Dołącz do gry</button>
                </div>
                <div class="menuBtn">
                    <button id="history" class="btn btn-primary" style="width: 70%;" data-bs-toggle="modal"
                        data-bs-target="#staticBackdrop2">Pokaż historie gier</button>
                </div>
                <div class="menuBtn">
                    <button id="howToPlay" class="btn btn-primary mb-2" data-bs-toggle="modal"
                        data-bs-target="#staticBackdrop3" style="width: 70%;">Jak grać</button>
                </div>

            </div>
            <div class="card-footer">
                <div class="btn "><a class="text-dark fw-bold" href="/logout">Wyloguj</a></div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <script src="../static/scripts/main.js"></script>

</body>


</html>

website/templates/new_account.html
<!DOCTYPE html>
<html lang="pl">

<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../static/styles.css">
    <link rel="icon" type="image/x-icon" href="../static/img/favicon.png">
    <title>Skrabble- rejestracja</title>

</head>

<body>

    <!--tło-->
    <div class='box'>
        <div class='wave -one'></div>
        <div class='wave -two'></div>
        <div class='wave -three'></div>
    </div>

    <!--nagłówek-->
    <div class="container-fluid text-center">
        <img src="../static/img/logo.png">
    </div>

    <!--karta do rejestracji-->
    <div class="container" style="position: relative; width: 30%; margin-top: 7%;">
        <div class="card" style="position: absolute;
        top: 50%;
        width: 100%;
        text-align: center;
        font-size: 18px;
        background-color: dodgerblue;
        border-radius: 25px;">
            <div class="card-body">
                <h4 class="card-title">Zarejestruj się</h4>
            </div>
            <div class="card-body">
                <form name="frm" action="{{ url_for('auth.new_account') }}" method="post">
                    <div class="form-group my-2">
                        <label for="userName">Nazwa użytkownika</label>
                        <input name="userName" type="text" class="form-control my-2" id="userName"
                            placeholder="Podaj nazwę użytkownika">
                    </div>
                    <div class="form-group my-2">
                        <label for="userEmail">Email</label>
                        <input name="userEmail" type="text" class="form-control my-2" id="userEmail"
                            placeholder="Podaj adres email">
                    </div>
                    <div class="form-group my-2">
                        <label for="userPassword">Hasło</label>
                        <input name="userPassword" type="text" class="form-control my-2" id="userPassword"
                            placeholder="Podaj hasło">
                    </div>
                    <div class="form-group mt-2 mb-4">
                        <label for="userPassword2">Powtórz hasło</label>
                        <input name="userPassword2" type="text" class="form-control mt-2 mb-0" id="userPassword2"
                            placeholder="Powtórz swoje hasło">
                        {% if message == "Email zajety" %}
                        <small name="warrning" id="passSame" class="form-text text-danger"
                            style="visibility:visable; position: absolute; bottom: 16%; left: 3%;text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue">
                            Istnieje już konto zarejestrowane na podany adres email.
                        </small>
                        {% else %}
                        <small name="warrning" id="passSame" class="form-text text-danger"
                            style="visibility:hidden; position: absolute; bottom: 16%; left: 3%;text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue"></small>
                        {% endif %}
                    </div>
                    <input class="btn btn-primary mt-2" type="submit" id="submitButton" value="Zarejestruj"
                        onclick="return isValid();">
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
        </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="../static/scripts/new_account.js"></script>
</body>

</html>